blueprint:
  name: Air Quality - Customizable Alert
  description: >
    This blueprint monitors air quality sensors for PM2.5, CO₂, and VOC levels and triggers alerts
    when sensor values are within defined thresholds. Customize the air quality type label (e.g. "moderate"),
    thresholds, icons, and the room/area. Optionally, select a light and/or scene to activate during the alert.
  domain: automation
  input:
    room:
      name: Room/Area
      description: "The room or area where the sensors are located."
      default: Living Room
      selector:
        text: {}
    air_quality_type:
      name: Air Quality Type
      description: "Label for the air quality type (e.g. moderate)."
      default: moderate
      selector:
        text: {}
    #
    # PM2.5 Settings
    #
    pm25_sensor:
      name: PM2.5 Sensor
      description: "Select the PM2.5 sensor."
      selector:
        entity:
          domain: sensor
    pm25_trigger_above:
      name: PM2.5 Trigger Above
      description: "Minimum PM2.5 value to trigger the alert."
      default: 9
      selector:
        number:
          mode: slider
          min: 0
          max: 500
    pm25_trigger_below:
      name: PM2.5 Trigger Below
      description: "Maximum PM2.5 value to trigger the alert."
      default: 35.5
      selector:
        number:
          mode: slider
          min: 0
          max: 500
    pm25_condition_below:
      name: PM2.5 Condition Below
      description: "Ensure PM2.5 value is below this threshold to validate the alert."
      default: 35.5
      selector:
        number:
          mode: slider
          min: 0
          max: 500
    pm25_icon:
      name: PM2.5 Icon
      description: "Icon to use in the PM2.5 notification (use mdi: format without file extension)."
      default: mdi:chemical-weapon
      selector:
        icon: {}
    #
    # CO₂ Settings
    #
    co2_sensor:
      name: CO₂ Sensor
      description: "Select the CO₂ sensor."
      selector:
        entity:
          domain: sensor
    co2_trigger_above:
      name: CO₂ Trigger Above
      description: "Minimum CO₂ value to trigger the alert."
      default: 799
      selector:
        number:
          mode: slider
          min: 0
          max: 5000
    co2_trigger_below:
      name: CO₂ Trigger Below
      description: "Maximum CO₂ value to trigger the alert."
      default: 1000
      selector:
        number:
          mode: slider
          min: 0
          max: 5000
    co2_condition_below:
      name: CO₂ Condition Below
      description: "Ensure CO₂ value is below this threshold to validate the alert."
      default: 1000
      selector:
        number:
          mode: slider
          min: 0
          max: 5000
    co2_icon:
      name: CO₂ Icon
      description: "Icon to use in the CO₂ notification (use mdi: format without file extension)."
      default: mdi:molecule-co2
      selector:
        icon: {}
    #
    # VOC Settings
    #
    voc_sensor:
      name: VOC Sensor
      description: "Select the VOC sensor."
      selector:
        entity:
          domain: sensor
    voc_trigger_above:
      name: VOC Trigger Above
      description: "Minimum VOC value to trigger the alert."
      default: 99
      selector:
        number:
          mode: slider
          min: 0
          max: 1000
    voc_trigger_below:
      name: VOC Trigger Below
      description: "Maximum VOC value to trigger the alert."
      default: 150
      selector:
        number:
          mode: slider
          min: 0
          max: 1000
    voc_icon:
      name: VOC Icon
      description: "Icon to use in the VOC notification (use mdi: format without file extension)."
      default: mdi:radiator
      selector:
        icon: {}
    #
    # Optional Actions
    #
    light_to_turn_on:
      name: Light to Turn On
      description: "Select a light to turn on during the alert (optional)."
      selector:
        entity:
          domain: light
      default: null
    scene_to_activate:
      name: Scene to Activate
      description: "Select a scene to activate during the alert (optional)."
      selector:
        entity:
          domain: scene
      default: null
    notification_service:
      name: Notification Service
      description: "Notification service to send alerts (e.g. notify.mobile_app_sm_s908u)."
      default: notify.mobile_app_sm_s908u
      selector:
        text: {}

trigger:
  - platform: device
    device_id: !input pm25_sensor
    domain: sensor
    entity_id: !input pm25_sensor
    type: pm25
    above: !input pm25_trigger_above
    below: !input pm25_trigger_below
    id: PM2.5
  - platform: device
    device_id: !input co2_sensor
    domain: sensor
    entity_id: !input co2_sensor
    type: carbon_dioxide
    above: !input co2_trigger_above
    below: !input co2_trigger_below
    id: CO2
  - platform: numeric_state
    entity_id: !input voc_sensor
    above: !input voc_trigger_above
    below: !input voc_trigger_below
    id: VOC

condition:
  - condition: and
    conditions:
      - condition: numeric_state
        entity_id: !input pm25_sensor
        below: !input pm25_condition_below
      - condition: numeric_state
        entity_id: !input co2_sensor
        below: !input co2_condition_below
      - condition: numeric_state
        entity_id: !input voc_sensor
        below: !input voc_trigger_below

action:
  # Notification actions based on which trigger fired.
  - choose:
      - conditions:
          - condition: trigger
            id: PM2.5
        sequence:
          - service: !input notification_service
            data:
              message: >-
                {{ air_quality_type | capitalize }} PM2.5 levels in {{ room }} have been detected.
              title: "{{ air_quality_type | capitalize }} PM2.5 Levels"
              data:
                clickAction: /lovelace/home
                url: /lovelace/home
                icon_url: "/local/icons/{{ pm25_icon | replace('mdi:', '') }}.png"
      - conditions:
          - condition: trigger
            id: CO2
        sequence:
          - service: !input notification_service
            data:
              message: >-
                {{ air_quality_type | capitalize }} CO₂ levels in {{ room }} have been detected.
                Recommend opening a window.
              title: "{{ air_quality_type | capitalize }} CO₂ Levels"
              data:
                clickAction: /lovelace/home
                url: /lovelace/home
                icon_url: "/local/icons/{{ co2_icon | replace('mdi:', '') }}.png"
      - conditions:
          - condition: trigger
            id: VOC
        sequence:
          - service: !input notification_service
            data:
              message: >-
                {{ air_quality_type | capitalize }} VOC levels in {{ room }} have been detected.
              title: "{{ air_quality_type | capitalize }} VOC Levels"
              data:
                clickAction: /lovelace/home
                url: /lovelace/home
                icon_url: "/local/icons/{{ voc_icon | replace('mdi:', '') }}.png"
  # Optional actions: turn on a light and/or activate a scene if configured.
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ light_to_turn_on is not none }}"
        sequence:
          - service: light.turn_on
            target:
              entity_id: !input light_to_turn_on
      - conditions:
          - condition: template
            value_template: "{{ scene_to_activate is not none }}"
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input scene_to_activate
mode: single
